name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
        env:
          CI: true
      - name: Build
        run: npm run build
      - name: Deploy
        env:
          actions_gh_pages_token: ${{ secrets.ACTIONS_GH_PAGES_TOKEN }}
        run: |
          git config --global user.name 'Huy Vuong'
          git config --global user.email 'huy-vuong@users.noreply.github.com'
          git remote set-url origin https://${actions_gh_pages_token}@github.com/huy-vuong/zenme-xie.git
          npm run deploy
